version: '3.8'

services:

  faiss:
    build:
      context: faiss
      dockerfile: Dockerfile
    container_name: faiss
    ports:
      - "5000:5000"
  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    container_name: agent
    ports:
      - "8000:8000"